import { apiGet } from "@/services/api";

const DASHBOARD_CACHE_KEY = "hirenest_dashboard_stats_v2";

export type DashboardCriterion = {
  key: string;
  label: string;
  complete: boolean;
  points: number;
  max_points: number;
  detail: string;
  action: string | null;
  href: string | null;
};

export type DashboardStats = {
  hasProfile: boolean;
  profileIsAutoGenerated: boolean;
  hasResume: boolean;
  resumeStatus: "missing" | "uploaded" | "parsed" | "extracted" | string;
  resumeStatusLabel: string;
  extractedSkills: number;
  experienceCount: number;
  educationCount: number;
  recommendedJobs: number;
  matchedJobs: number;
  activeJobOffers: number;
  qcmCompleted: number;
  interviewCompleted: number;
  recommendationProgress: number;
  recommendationProgressLabel: string;
  recommendationProgressDetail: string;
  nextAction: string;
  nextActionHref: string;
  criteria: DashboardCriterion[];
  lastUpdatedAt: string;
  source: "live" | "offline-cache";
};

type DashboardStatsApi = {
  has_profile: boolean;
  profile_is_auto_generated: boolean;
  has_resume: boolean;
  resume_status: string;
  resume_status_label: string;
  extracted_skills: number;
  experience_count: number;
  education_count: number;
  recommended_jobs: number;
  matched_jobs: number;
  active_job_offers: number;
  qcm_completed: number;
  interview_completed: number;
  recommendation_progress: number;
  recommendation_progress_label: string;
  recommendation_progress_detail: string;
  next_action: string;
  next_action_href: string;
  criteria: DashboardCriterion[];
  last_updated_at: string;
  source: "live";
};

function fromApi(data: DashboardStatsApi): DashboardStats {
  return {
    hasProfile: data.has_profile,
    profileIsAutoGenerated: data.profile_is_auto_generated,
    hasResume: data.has_resume,
    resumeStatus: data.resume_status,
    resumeStatusLabel: data.resume_status_label,
    extractedSkills: data.extracted_skills,
    experienceCount: data.experience_count,
    educationCount: data.education_count,
    recommendedJobs: data.recommended_jobs,
    matchedJobs: data.matched_jobs,
    activeJobOffers: data.active_job_offers,
    qcmCompleted: data.qcm_completed,
    interviewCompleted: data.interview_completed,
    recommendationProgress: data.recommendation_progress,
    recommendationProgressLabel: data.recommendation_progress_label,
    recommendationProgressDetail: data.recommendation_progress_detail,
    nextAction: data.next_action,
    nextActionHref: data.next_action_href,
    criteria: data.criteria,
    lastUpdatedAt: data.last_updated_at,
    source: data.source,
  };
}

function readCache(): DashboardStats | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(DASHBOARD_CACHE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as DashboardStats;
  } catch {
    return null;
  }
}

function writeCache(stats: DashboardStats) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(
    DASHBOARD_CACHE_KEY,
    JSON.stringify({ ...stats, source: "offline-cache" }),
  );
}

export function getCachedDashboardStats() {
  return readCache();
}

export async function fetchDashboardStats(): Promise<DashboardStats> {
  const stats = fromApi(await apiGet<DashboardStatsApi>("/dashboard/me", {
    cacheTtlMs: 30_000,
  }));
  writeCache(stats);
  return stats;
}
