"use client";

import {
  BarChart3,
  Briefcase,
  ClipboardCheck,
  FileText,
  RefreshCw,
  Video,
} from "lucide-react";
import Link from "next/link";

import { ActionCard } from "@/components/dashboard/ActionCard";
import { RecentActivity } from "@/components/dashboard/RecentActivity";
import { StatCard } from "@/components/dashboard/StatCard";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useAuth } from "@/hooks/useAuth";
import { useDashboardStats } from "@/hooks/useDashboardStats";

type StatTone = "default" | "good" | "warning" | "danger";

const actions = [
  {
    title: "Review Resume",
    description:
      "Upload a CV and receive AI feedback on structure, ATS fit, and skills.",
    href: "/resume",
    icon: FileText,
    cta: "Start Review",
  },
  {
    title: "Explore Job Offers",
    description:
      "Browse recommended offers ranked by skill fit and career trajectory.",
    href: "/jobs",
    icon: Briefcase,
    cta: "Browse Jobs",
  },
  {
    title: "Prepare QCM",
    description:
      "Track technical assessments and recommended preparation topics.",
    href: "/qcm",
    icon: ClipboardCheck,
    cta: "Open Tests",
  },
  {
    title: "AI Interview",
    description:
      "Practice structured interviews with clarity and confidence signals.",
    href: "/interview",
    icon: Video,
    cta: "Start Practice",
  },
];

export default function DashboardPage() {
  const { user } = useAuth();
  const { stats, loading, refreshing, error, isOfflineData, refresh } = useDashboardStats();
  const displayName =
    [user?.first_name, user?.last_name].filter(Boolean).join(" ").trim() ||
    user?.fullName ||
    user?.username ||
    user?.email ||
    "candidate";
  const lastUpdated = stats?.lastUpdatedAt
    ? new Date(stats.lastUpdatedAt).toLocaleString()
    : null;
  const dashboardStats = [
    {
      label: "Resume Status",
      value:
        loading && !stats
          ? "Loading"
          : stats?.resumeStatusLabel ?? "No CV",
      detail: isOfflineData
        ? `Offline data${lastUpdated ? ` - ${lastUpdated}` : ""}`
        : stats?.resumeStatus === "extracted"
          ? `${stats.extractedSkills} skills, ${stats.experienceCount} experiences, ${stats.educationCount} education items extracted`
          : stats?.resumeStatus === "parsed"
            ? "Resume parsed. Run structured extraction to unlock better matching."
            : stats?.resumeStatus === "uploaded"
              ? "Resume uploaded. Parse it to continue."
          : "Upload and parse a CV to unlock analysis",
      icon: FileText,
      tone: (stats?.resumeStatus === "extracted" ? "good" : stats?.hasResume ? "warning" : "default") as StatTone,
    },
    {
      label: "Recommended Jobs",
      value:
        loading && !stats ? "Loading" : String(stats?.recommendedJobs ?? 0),
      detail: isOfflineData
        ? `Offline data${lastUpdated ? ` - ${lastUpdated}` : ""}`
        : stats?.matchedJobs
          ? `${stats.matchedJobs} personalized matches from ${stats.activeJobOffers} active offers`
          : stats?.activeJobOffers
            ? `${stats.activeJobOffers} active offers available. Generate matches to personalize them.`
            : "No active offers are available yet.",
      icon: Briefcase,
      tone: (stats?.matchedJobs ? "good" : stats?.activeJobOffers ? "warning" : "default") as StatTone,
    },
    {
      label: "Recommendation Progress",
      value:
        loading && !stats
          ? "Loading"
          : `${stats?.recommendationProgress ?? 0}%`,
      detail: error ?? stats?.recommendationProgressDetail ?? "Based on profile, resume, extraction, matching, and evaluations",
      icon: BarChart3,
      progress: stats?.recommendationProgress ?? 0,
      tone:
        (stats?.recommendationProgress ?? 0) >= 80
          ? "good"
          : (stats?.recommendationProgress ?? 0) >= 40
            ? "warning"
            : "default" as StatTone,
    },
  ];
  const incompleteCriteria = stats?.criteria.filter((item) => !item.complete) ?? [];
  const activity = [
    {
      title: stats?.hasProfile
        ? stats?.profileIsAutoGenerated
          ? "Profile auto-generated"
          : "Profile available"
        : "Profile not created",
      description: stats?.hasProfile
        ? stats?.profileIsAutoGenerated
          ? "Your profile was automatically generated from your CV. You can edit it in Settings."
          : "Your candidate profile is ready."
        : "Upload and parse a CV to auto-generate your profile.",
      time: lastUpdated ?? "live check",
      icon: BarChart3,
    },
    {
      title:
        stats?.resumeStatus === "parsed"
          ? "Resume parsed"
          : stats?.resumeStatus === "uploaded"
            ? "Resume uploaded"
            : "Resume missing",
      description:
        stats?.resumeStatus === "parsed"
          ? "Parsed CV text is ready for extraction and matching."
          : stats?.resumeStatus === "uploaded"
            ? "Parse the uploaded CV to enable structured extraction."
            : "Upload your resume to start analysis.",
      time: lastUpdated ?? "live check",
      icon: FileText,
    },
    {
      title: stats?.recommendedJobs ? "Job offers available" : "No offers yet",
      description: stats?.matchedJobs
        ? `${stats.matchedJobs} personalized matches are ready from ${stats.activeJobOffers} active offers.`
        : stats?.activeJobOffers
          ? `${stats.activeJobOffers} offers are available, but personalized matches are not ready yet.`
          : "Import or load job offers to start matching.",
      time: lastUpdated ?? "live check",
      icon: Briefcase,
    },
    {
      title: stats?.qcmCompleted || stats?.interviewCompleted ? "Evaluation started" : "No evaluation completed",
      description: stats?.qcmCompleted || stats?.interviewCompleted
        ? `${stats.qcmCompleted} QCM and ${stats.interviewCompleted} AI interview sessions completed.`
        : "Complete a QCM or AI interview to improve your readiness score.",
      time: lastUpdated ?? "live check",
      icon: ClipboardCheck,
    },
  ];

  return (
    <DashboardLayout>
      <main className="mx-auto w-full max-w-7xl space-y-8 px-4 py-4 sm:px-6 sm:py-6 lg:px-8 lg:py-8">
        <section className="rounded-3xl bg-[#020817] p-8 text-white shadow-sm md:p-10">
          <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
            <div className="max-w-3xl">
              <p className="text-sm font-semibold text-sky-300">
                HireNest AI Workspace
              </p>
              <h1 className="mt-3 text-2xl font-bold sm:text-4xl">
                Welcome back, {displayName}.
              </h1>
              <p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">
                Track your candidate profile, resume status, and available job
                matches from one clean dashboard.
              </p>
              {!loading && stats && !stats.hasProfile ? (
                <p className="mt-4 rounded-2xl border border-sky-400/30 bg-white/10 px-4 py-3 text-sm text-sky-100">
                  Complete your profile or upload a resume before recommendations can become fully personalized.
                </p>
              ) : !loading && stats && stats.profileIsAutoGenerated ? (
                <p className="mt-4 rounded-2xl border border-emerald-400/30 bg-white/10 px-4 py-3 text-sm text-emerald-100">
                  Your profile is currently inferred from CV data. Edit it in Settings to personalize your target role.
                </p>
              ) : null}
            </div>
            <div className="flex flex-col items-start gap-3 sm:flex-row lg:items-center">
              {stats ? (
                <Badge className="rounded-full bg-white/10 px-4 py-2 text-white hover:bg-white/10">
                  {stats.recommendationProgressLabel}
                </Badge>
              ) : null}
              <Button
                type="button"
                variant="secondary"
                className="rounded-xl bg-white text-slate-950 hover:bg-slate-100"
                disabled={loading || refreshing}
                onClick={() => void refresh()}
              >
                <RefreshCw className={`mr-2 h-4 w-4 ${refreshing ? "animate-spin" : ""}`} />
                {refreshing ? "Refreshing" : "Refresh"}
              </Button>
            </div>
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-3 lg:gap-6">
          {dashboardStats.map((stat) => (
            <StatCard key={stat.label} {...stat} loading={loading && !stats} />
          ))}
        </section>

        <section className="grid gap-4 lg:grid-cols-[1fr_360px] lg:gap-6">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition-all duration-200">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <h2 className="text-lg font-bold text-slate-950">Recommendation readiness</h2>
                <p className="mt-1 text-sm text-slate-500">
                  Progress is calculated from backend criteria, not from fake defaults.
                </p>
              </div>
              {stats ? (
                <Badge className="rounded-full bg-sky-50 px-3 py-1.5 text-sky-700 hover:bg-sky-50">
                  {stats.recommendationProgress}% complete
                </Badge>
              ) : null}
            </div>
            <div className="mt-5 grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4">
              {loading && !stats ? (
                Array.from({ length: 8 }).map((_, index) => (
                  <Skeleton key={index} className="h-20 rounded-2xl" />
                ))
              ) : (
                stats?.criteria.map((criterion) => (
                  <div
                    key={criterion.key}
                    className={`min-w-0 overflow-hidden rounded-2xl border p-4 transition-all duration-200 ${
                      criterion.complete
                        ? "border-emerald-100 bg-emerald-50"
                        : "border-slate-200 bg-slate-50"
                    }`}
                  >
                    <div className="flex min-w-0 flex-wrap items-start justify-between gap-2">
                      <p className="min-w-0 break-words font-semibold text-slate-950">{criterion.label}</p>
                      <Badge className={(criterion.complete ? "bg-emerald-100 text-emerald-700" : "bg-white text-slate-600") + " shrink-0"}>
                        {criterion.points}/{criterion.max_points}
                      </Badge>
                    </div>
                    <p className="mt-2 break-words text-sm leading-6 text-slate-600">{criterion.detail}</p>
                  </div>
                ))
              )}
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 className="text-lg font-bold text-slate-950">Next best action</h2>
            {loading && !stats ? (
              <div className="mt-4 space-y-3">
                <Skeleton className="h-4 w-full rounded-xl" />
                <Skeleton className="h-10 w-full rounded-xl" />
              </div>
            ) : (
              <>
                <p className="mt-2 text-sm leading-6 text-slate-500">
                  {stats?.nextAction || "Load dashboard data to see the next action."}
                </p>
                <Button asChild className="mt-4 w-full rounded-xl">
                  <Link href={stats?.nextActionHref || "/resume"}>
                    Continue
                  </Link>
                </Button>
                {incompleteCriteria.length ? (
                  <p className="mt-3 text-xs leading-5 text-slate-400">
                    {incompleteCriteria.length} readiness item{incompleteCriteria.length === 1 ? "" : "s"} still incomplete.
                  </p>
                ) : null}
              </>
            )}
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-2 lg:gap-6 xl:grid-cols-4">
          {actions.map((action) => (
            <ActionCard key={action.title} {...action} />
          ))}
        </section>

        <RecentActivity items={activity} />
      </main>
    </DashboardLayout>
  );
}
